### ISSUE TITLE
isOnGround()

### ISSUE THREAD

**Issue by NotRhian** [awesome90/Crescent#1]
Make a server side check for players being on ground. Developers can easily bypass a client side check

**Comment by NotRhian** [comment]
same thing with like water and shit

**Comment by awesome90** [comment]
Perhaps we could use the World#getHighestBlockYAt method and then compare the player's y coordinate with this?

**Comment by NotRhian** [comment]
yeah that would work fine. tbh the playerutil in one of the versions of janitor even patched this. you can use that as an example the anti cheat is looking good tho

**Comment by awesome90** [comment]
Cool. Is there a GitHub repository page for Janitor?
Thanks for your kind words about the anticheat, it's really appreciated. Feel free if you want to submit a pull request ever! If, not I'm still very happy you're interested. 😄

**Comment by NotRhian** [comment]
Heres the class in general. http://pastebin.com/8zz2armf

**Comment by NotRhian** [comment]
Also use vectors for calculating reach other wise youll get false positives. didnt know if you already did so or not

**Comment by awesome90** [comment]
Thanks for the class! I use the Location#distanceSquared method for calculating reach. Why would using vectors be better?

**Comment by NotRhian** [comment]
I dont think I really need to explain it all that much. Trying to calculate the distance your bound to get false positives with vectors you can work on getting rid of those false positives. Thats what zonix, lounge, opticcraft, gcheat, etc does

**Comment by NotRhian** [comment]
also wrote a little aimbot check you can base your things of off http://pastebin.com/77BU2fEh

**Comment by NotRhian** [comment]
I would use vectors for a majority of combat checks you use their better most of the time

**Comment by awesome90** [comment]
Yes, I suppose that's true. Thank you for the advice. And as for the aimbot check, you should submit that as a pull request!

**Comment by NotRhian** [comment]
Ill submit a pull request later. Its 10am and I think its time to get some sleep. The aim bot check is basic I have a smooth aim check ive been working on as well. Also I was reading your machine learning and it really interest me

**Comment by NotRhian** [comment]
also one more question why are you using final everything? its useless tbh

**Comment by awesome90** [comment]
Well, the machine learning check isn't exactly too complicated but it seems to actually work very well.

I'm using final to indicate that the variable shouldn't change. I agree it's making everything kinda messy so I might change it back later.

**Comment by awesome90** [comment]
I've made progress on this in e7f50cc561f84224b49999ccb081307edcc087bf

**Comment by awesome90** [comment]
I added an isOnGround method. It seems to be working well.
