### ISSUE TITLE
AntiKnockback Check not working.

### ISSUE THREAD

**Issue by Eyremba** [awesome90/Crescent#2]
What if a player...

- is in Cobweb?

- is on a Ladder?

- is in Water/Lava? (knockback strongly reduced there)

- is standing in front of a wall? (Knockback physically NOT possible)

There are so many situations which have to be checked before a player should get flagged for AntiKnockback...

**Comment by awesome90** [comment]
Cobweb - Yes, I agree. I'll add that.
Ladder - I also agree,
Water/Lava - No, because the check checks for changes in y values. You're still pushed up here.
Standing in front of a wall - You're still pushed upwards here.

Thanks for your suggestions 😄 I'll add cobweb and ladder checks 👍

**Comment by awesome90** [comment]
Added with 3983b756fb5c5ef182bfdc73c7deb2250ff4df30

**Comment by Eyremba** [comment]
> Standing in front of a wall - You're still pushed upwards here.

And if you are in a minewith 2x1 or 2x2 tunnels and get hit there? Or another spot where something is above your head? :D

**Comment by awesome90** [comment]
Yeah, you're still pushed upwards here. I just tested it with Crescent on and there are no false positives. Let me know if you find any! :D

**Comment by awesome90** [comment]
Update: Just found that if you are jumping while being pushed back in a 2v1 hole, false positives occur.

**Comment by awesome90** [comment]
This should be fixed with aa0ddc41e112ecde392557ac187ada784266a8c9
